---
# Source: helm for kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kongden-next-js-app-v2-yarn          # Service name
  labels:
    app: kongden-next-js-app-v2-yarn
spec:
  type: ClusterIP   # Service type (ClusterIP, NodePort, LoadBalancer)
  selector:
    app: kongden-next-js-app-v2-yarn         # Matches Deployment labels
  ports:
    - protocol: TCP
      port: 3000         # Service port
      targetPort: 3000  # Target container port
